addons:
  sauce_connect:
    username: "alexdebian"
    access_key: "c52d2334-38f0-4ada-bc5a-bf6691258853"

language: python
python:
  - '3.5'

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script: python3 -m unittest -v testcalc_remote