addons:
  firefox: "50.1"

language: python
python:
  - '3.5'

#before install:
#  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
#  - tar xf geckodriver-v0.11.1-linux64.tar.gz
#  - sudo cp $TRAVIS_BUILD_DIR/geckodriver /usr/bin/geckodriver
#  - sudo mv $TRAVIS_BUILD_DIR/geckodriver /usr/bin/wires
#  - export PATH=/usr/bin:$PATH

install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - tar xf geckodriver-v0.11.1-linux64.tar.gz
  - sudo cp $TRAVIS_BUILD_DIR/geckodriver /usr/bin/geckodriver
  - sudo mv $TRAVIS_BUILD_DIR/geckodriver /usr/bin/wires
  - export PATH=/usr/bin:$PATH
  - sudo pip3 install selenium

script: python3 -m unittest -v testcalc