addons:
  firefox: "50.1.0"

language: python
python:
  - '3.5'

install:
#  - travis_wait 20 mvn install
  - sudo apt-get install xvfb
  - pip install --upgrade pip
  - ls
  - pip install -r requirements.txt
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - tar xf geckodriver-v0.11.1-linux64.tar.gz
  - sudo cp $TRAVIS_BUILD_DIR/geckodriver /usr/bin/geckodriver
#  - sudo mv $TRAVIS_BUILD_DIR/geckodriver /usr/bin/wires
  - export PATH=$PATH:/usr/bin

script: python3 -m unittest -v testcalc.TestCalculator.test_summing_int_numbers