addons:
  sauce_connect:
    username: "alexdebian"
    access_key: "c52d2334-38f0-4ada-bc5a-bf6691258853"

language: python
python:
  - '3.5'

install:
#  - pip install --upgrade pip
#  - ls
#  - pip install -r requirements.txt
#  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
#  - tar xf geckodriver-v0.11.1-linux64.tar.gz
#  - sudo cp $TRAVIS_BUILD_DIR/geckodriver /usr/bin/geckodriver
#  - sudo mv $TRAVIS_BUILD_DIR/geckodriver /usr/bin/wires
#  - export PATH=$PATH:/usr/bin

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script: python3 -m unittest -v testcalc_remote.TestCalculator.test_summing_int_numbers