addons:
  firefox: "50.1"

language: python
python:
  - '3.5'

install:
#  - sudo pip install selenium==3.0.2
  - pip install .
  - pip install -r requirements.txt
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - tar xf geckodriver-v0.11.1-linux64.tar.gz
  - sudo cp $TRAVIS_BUILD_DIR/geckodriver /usr/bin/geckodriver
  - sudo mv $TRAVIS_BUILD_DIR/geckodriver /usr/bin/wires
  - export PATH=/usr/bin:$PATH

script: python3 -m unittest -v testcalc